# Generated by Django 4.0 on 2021-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_raters',
            field=models.IntegerField(default=0),
        ),
    ]
